### ISSUE TITLE
Cannot create several aggregates at once using count or for_each (GCP).

### ISSUE THREAD

**Issue by dbilostotskyi-clgx** [NetApp/terraform-provider-netapp-cloudmanager#101]
Having an issue with multiple aggregates creation when using count or for_each statement. Terraform creates only the first defined from the  list and then gives the error:

11:41:41  module.aggregate["aggregate_cfg3"].netapp-cloudmanager_aggregate.cl-aggregate: Creation complete after 3m35s [id=what_aggr_3]
11:41:41  
11:41:41  Error: code: 409, message: {"message":"Couldn't perform action Create Aggregate, because there are ongoing operations which might interfere with it: Create Aggregate","causeMessage":"OnGoingAsyncOperationException: Couldn't perform action Create Aggregate, because there are ongoing operations which might interfere with it: Create Aggregate"}

**Comment by chuyich** [comment]
Are these aggregates going to be created on the same gcp CVO?

**Comment by chuyich** [comment]
This is a serial operation in cloudmanager. It does not queue, so it reports errors. Please use terraform flag **-parallelism=1** to disable the parallelism. "terraform apply -parallelism=1"

**Comment by chuyich** [comment]
DEVOPS-5146

**Comment by chuyich** [comment]
Fix on version 22.8.0
