### ISSUE TITLE
support attaching existing role to connector

### ISSUE THREAD

**Issue by nichollri** [NetApp/terraform-provider-netapp-cloudmanager#102]
In the cloud manager SaaS UI when deploying a connector you can select an existing role to apply to the connector.  Terraform deployment of the connector does not support a pre-existing role to attach.  This functionality needs to be added.
It currently allows you to name the instance profile but not to have a role that already exists.

![image](https://user-images.githubusercontent.com/519212/174532286-8443aabe-707d-49a9-a4fe-062744c53fec.png)

**Comment by nichollri** [comment]
Closing this request.  I misinterpreted, the AWS connector terraform allows you to use an existing instance profile/role with the "iam_instance_profile_name".  I just validated this on a deployment. I am closing this now, sorry for the confusion.

**Comment by lonico** [comment]
Should we clarify this in teh documentation?

**Comment by suhasbshekar** [comment]
Can this issue be closed now?
