### ISSUE TITLE
CVO VM type change requires CVO recreation (GCP)

### ISSUE THREAD

**Issue by melatsg** [NetApp/terraform-provider-netapp-cloudmanager#104]
Hello,

When I am trying to change the GCE type of the CVO, the CVO is being recreated if the "writing_speed_state" argument is not specified:
![Screenshot 2022-06-27 at 15 44 30](https://user-images.githubusercontent.com/71067709/175956447-5569f6eb-7380-47a6-9817-0f3aad370527.png)

If I specify the "writing_speed_state" argument there is no need to recreate the CVO instead. 

I believe that the expected behaviour is the second one, a GCE change should not need the recreation of the CVO, and that there is an issue with the "writing_speed_state" argument that is an optional one.

Thanks

**Comment by lonico** [comment]
DEVOPS-5237

**Comment by wenjun666** [comment]
fixed in v22.8.0
