### ISSUE TITLE
Setting Ontap Version gives InvalidMetadataException. GCP CVO-HA

### ISSUE THREAD

**Issue by dbilostotskyi-clgx** [NetApp/terraform-provider-netapp-cloudmanager#105]
Hello,
Whichever version I try to set with **ontap_version** I get the following error:
"InvalidMetadataException: There is no valid configuration for Ontap Version 9.11.0P1.
I also tried 9.10, 9.10.1, 9.10.3, and 9.11.1. 
Could you please advise if my version formats are wrong?
Thanks

**Comment by chuyich** [comment]
For GCP HA, the version format is  "ONTAP-xxxx.gcpha"
Here is an example  **ontap_version = "ONTAP-9.9.1P3.T1.gcpha"**

**Comment by dbilostotskyi-clgx** [comment]
Thanks a lot! It works.
