### ISSUE TITLE
NetApp provider not found on Hashicorp

### ISSUE THREAD

**Issue by mldmld68** [NetApp/terraform-provider-netapp-cloudmanager#109]
Hi all
I start with CVO.
I'm trying to install a Cloud Manager on GCP, but I get this error.

See forward.

This code is running as a Service account. Should I need to setup some permission on NetApp Central ? Where ?  
Thank you
MLD
In the code I set : 
```
provider "google" {
  region  = "europe-west1"
  project = var.PROJECT_ID
}

provider "google-beta" {
  region  = "europe-west1"
  project = var.PROJECT_ID
}

provider "netapp-cloudmanager" {
#  refresh_token         = var.cloudmanager_refresh_token
#  sa_secret_key         = var.cloudmanager_sa_secret_key
#  sa_client_id          = var.cloudmanager_sa_client_id
#  aws_profile           = var.cloudmanager_aws_profile
}

terraform {
  backend "gcs" {}
}

```
And I get 

Initializing provider plugins...
- Finding latest version of hashicorp/google-beta...
- Finding latest version of hashicorp/google...
- Finding latest version of hashicorp/netapp-cloudmanager...
- Installing hashicorp/google-beta v4.31.0...
- Installed hashicorp/google-beta v4.31.0 (signed by HashiCorp)
- Installing hashicorp/google v4.31.0...
- Installed hashicorp/google v4.31.0 (signed by HashiCorp)
Error: Failed to install provider
Error while installing hashicorp/netapp-cloudmanager: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/netapp-cloudmanager
ERROR: Job failed: exit code 1

**Comment by lonico** [comment]
https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/latest

Click on `USE PROVIDER`

Maybe you need
```
terraform {
  required_providers {
    netapp-cloudmanager = {
      source = "NetApp/netapp-cloudmanager"
      version = "22.4.0"
    }
  }
}
```

**Comment by lonico** [comment]
Closing as the provider is in the registry.  Please note that there are newer releases now,

Contact us on discord on the #terraform channel at https://discord.gg/netapp
