### ISSUE TITLE
Credentials error while creating CVO

### ISSUE THREAD

**Issue by nutanksingh** [NetApp/terraform-provider-netapp-cloudmanager#115]
Hi I have a terraform plan that I run from terraform Enterprise to deploy netapp cluster in our AWS account.
Screenshot for my code structure is attached.
I am creating Connector and CVO by calling it's own module. I use IAM Role which trusts the 3rd party(netapp's) AWS account.
We are passing the credentials through the IAM instance profile. Connector gets created fine but I get an error for CVO.

Please note that I pass the AWS access and secret key in the Environment variables of the terraform workspace. All resources like key_pair, security group rules and connector gets created just fine as you can see on the screenshot but CVO creation fails.

Screenshot of error attached. Cloud you look at this and provide appropriate guidance?

<img width="201" alt="Screen Shot 2022-08-08 at 4 45 49 PM" src="https://user-images.githubusercontent.com/8824315/183533690-1ff5e46b-5a4a-42c0-81fa-c837f6fcaa82.png">

<img width="1266" alt="Screen Shot 2022-08-08 at 4 42 29 PM" src="https://user-images.githubusercontent.com/8824315/183533622-52b00a56-fc5d-4641-b806-ee2231779b3d.png">

**Comment by nutanksingh** [comment]
this is how module/cvo.tf file look like

##########################

resource "netapp-cloudmanager_cvo_aws" "this" {
  name   = var.cluster_name
  region = var.region

  instance_profile_name          = var.instance_profile_name
  mediator_instance_profile_name = var.instance_profile_name

  svm_password = var.password
  client_id    = var.connector
  vpc_id       = data.aws_vpc.this.id
  workspace_id = var.workspace_id

  ebs_volume_size      = var.ebs_volume_size
  ebs_volume_size_unit = var.ebs_volume_size_unit
  ebs_volume_type      = var.ebs_volume_type
  iops                 = 3000
  throughput           = 125

  ontap_version         = var.ontap_version
  use_latest_version    = var.use_latest_version
  license_type          = "ha-capacity-paygo"
  capacity_package_name = var.capacity_package_name
  instance_type         = var.instance_type

  is_ha                          = true
  failover_mode                  = "FloatingIP"
  node1_subnet_id                = data.aws_subnet.a.id
  node2_subnet_id                = data.aws_subnet.b.id
  mediator_subnet_id             = data.aws_subnet.c.id
  mediator_key_pair_name         = var.key_name

  cluster_floating_ip        = var.floating_ips["cluster"]
  data_floating_ip           = var.floating_ips["data1"]
  data_floating_ip2          = var.floating_ips["data2"]
  svm_floating_ip            = var.floating_ips["svm"]
  route_table_ids            = data.aws_route_tables.this.ids

  upgrade_ontap_version      = var.upgrade_ontap_version

  dynamic "aws_tag" {
   for_each = var.common_tags
   content {
     tag_key   = aws_tag.key
     tag_value = aws_tag.value
   }
 }
  depends_on = [
    aws_security_group.cvo
  ]
}

**Comment by nutanksingh** [comment]
I am not sure where's provider looking for the credentials while creating the CVO. 
If it accepts the access/secret key from TFE environment variable then it should probably complain for not enough permission at worst.
Or If it's using the IAM instance profile same as that of connector then it doesn't need Access/secret key.

**Comment by wenjun666** [comment]
Hi @nutanksingh, access key or secret key is not needed in cvo operations, so I am not sure where the error coming from. Can enable logging 'export TF_LOG=DEBUG'?

**Comment by nutanksingh** [comment]
logs

[run-MmPQ5x1z1SLdKCJN-apply-log.txt](https://github.com/NetApp/terraform-provider-netapp-cloudmanager/files/9295526/run-MmPQ5x1z1SLdKCJN-apply-log.txt)

**Comment by wenjun666** [comment]
In the provider, aws credential is not needed to create CVO, I have to contact the cvo team for more info.

**Comment by edarzi** [comment]
they keys required are for the Connector creation, the creation of the CVO will use the credentials of the connector
means when you create the connector you gave role to the instance with required permission.
please verify there is indeed role assigned to the machine with the required permission

**Comment by nutanksingh** [comment]
Hi Eran,
 I have figured out the issue. So, we don't assign permission to IAM user directly but we let the user assume a role which has all the permissions. I learned that this provider doesn't support assume role . I think that might be the reason of this issue.
After I assigned permissions to the user directly instead of assume role, it seems to work fine.

It would be great if you could make this note in your provider documentation.

**Comment by lonico** [comment]
Yes assume role is not supported at present.

**Comment by lonico** [comment]
DEVOPS-5350
