### ISSUE TITLE
Error: Taking too long for OCCM agent to be active or not properly setup

### ISSUE THREAD

**Issue by kenkraus** [NetApp/terraform-provider-netapp-cloudmanager#118]
Receiving this error when creating cloud manager connector in AWS with TF.   It creates the EC2 instance in AWS just fine, but errors out.  This appears to be some sort of timing issue.

**Comment by kenkraus** [comment]
[run-tQF1ag46ZYL9EnXD-apply-log.txt](https://github.com/NetApp/terraform-provider-netapp-cloudmanager/files/9329269/run-tQF1ag46ZYL9EnXD-apply-log.txt)

**Comment by suhasbshekar** [comment]
can you send the playbook (.tf) file which is used?

**Comment by kenkraus** [comment]
[ehi_cloudmanager.zip](https://github.com/NetApp/terraform-provider-netapp-cloudmanager/files/9329457/ehi_cloudmanager.zip)

Here are our .tf playbook files.  I had to modify a couple vars to protect our IP space and refresh token.  Hope that is still helpful?

**Comment by chuyich** [comment]
Can you provide the log? Run the following command:
**TF_LOG="DEBUG" terraform apply**

**Comment by kenkraus** [comment]
I think we can safely close out this issue.  The issue was with my security group egress rules.   Once we manually allow all egress, the cloud manager connector starts working.  The timeout was related to not being able to communicate.

Our TFE was preventing egress wide open, so I had to limit with egress with several CIDR block rules.

**Comment by chuyich** [comment]
Thanks for the update!
