### ISSUE TITLE
Mediator security group option on netapp-cloudmanager_cvo_aws

### ISSUE THREAD

**Issue by bryanheo** [NetApp/terraform-provider-netapp-cloudmanager#119]
Hello

When we define security_group_id on netapp-cloudmanager_cvo_aws, it only applies to nodes rather than mediator. I cannot find any option to apply the custom security group to mediator. The mediator's subnet CIDR only appears on the rule with 3000 port. Is it intended or is there any way to customise mediator security group?

Regards
Moon

**Comment by wenjun666** [comment]
We will add that option is our provider.

**Comment by bryanheo** [comment]
@wenjun666 Thank you
Yes, I can see the option on Cloud Manager but not in TF.
Could you let me know ETA for this option?
 
![Screenshot 2022-08-16 at 11 00 04](https://user-images.githubusercontent.com/12592663/184853114-8e18b981-6dac-4fa4-a159-6d40967a0496.png)

**Comment by lonico** [comment]
DEVOPS-5335

**Comment by wenjun666** [comment]
This should be released by this Thursday.

**Comment by bryanheo** [comment]
@wenjun666 Thank you

**Comment by wenjun666** [comment]
fixd in v22.8.3
