### ISSUE TITLE
Encryption on S3 bucket in AWS

### ISSUE THREAD

**Issue by bryanheo** [NetApp/terraform-provider-netapp-cloudmanager#120]
Hello

Unlike GCP, AWS S3 does not seem to be encrypted. We have defined aws_encryption_kms_key_id with custom KMS key and even we tried default encryption but EBS is encrypted only. Is there any ways to encrypt S3 bucket via the options in netapp-cloudmanager_cvo_aws?

![Screenshot 2022-08-15 at 20 37 09](https://user-images.githubusercontent.com/12592663/184705659-09659f11-fe58-4ef2-8f17-a9a1e44ddfe3.png)

Regards
Moon

**Comment by bryanheo** [comment]
I can see the objects are encrypted in S3 but S3 bucket is not encrypted.
Is it intended? Are there any other options to use customer-managed-key for S3 encryption rather than using default aws/s3 key?  

![Screenshot 2022-08-16 at 11 19 58](https://user-images.githubusercontent.com/12592663/184856815-0d33f836-94e6-4da1-b133-9f4855917828.png)

![Screenshot 2022-08-16 at 12 04 26](https://user-images.githubusercontent.com/12592663/184865231-60bc97b2-5ef1-4bb6-b0e8-f14cadc6a912.png)

**Comment by edarzi** [comment]
Currently only the objects encrypted, raise request to the DEV team to enable bucket encryption as well.
shall be available on mid September.
the key which is used during creation will apply both for EBS and the S3

**Comment by bryanheo** [comment]
@edarzi Thank you
