### ISSUE TITLE
There is no Node Key Pair option in netapp-cloudmanager_cvo_aws

### ISSUE THREAD

**Issue by bryanheo** [NetApp/terraform-provider-netapp-cloudmanager#121]
Hello

I can see mediator_key_pair_name option but there is no Node Key Pair option in netapp-cloudmanager_cvo_aws. 
Unlike Cloud manager, the nodes use password SSH authentication method only in netapp-cloudmanager_cvo_aws. 
Is it intended or is there any other ways to use Key pair on the nodes?

![Screenshot 2022-08-16 at 11 10 11](https://user-images.githubusercontent.com/12592663/184854659-a0d9bbce-fa2f-4bc9-8416-aeaee5cfae79.png)

Regards
Moon

**Comment by chuyich** [comment]
DEVOPS-5346

**Comment by wenjun666** [comment]
fixed in v22.8.3
