### ISSUE TITLE
SVM Support for Managing Multiple SVMs through Cloud Manager!

### ISSUE THREAD

**Issue by rpdowler** [NetApp/terraform-provider-netapp-cloudmanager#125]
I'm a NetApp GCP Cloud Solutions Architect and I have a customer who wants to have the capability to manage multiple SVMs through terraform. Currently there is no field in our volume deployment resource for specifying 'SVM', and we also do not have the capability to create an SVM resource. The capability to support multiple SVMs was just recently released so I just wanted to raise an issue to eventually bring support for this feature!

**Comment by chuyich** [comment]
svm_name is the field on the resource netapp-cloudmanager_volume. https://github.com/NetApp/terraform-provider-netapp-cloudmanager/issues/93 has been raised for adding the multiple GCP HA SVM. And we have an internal JIRA for this.

**Comment by lonico** [comment]
The feature was pulled off, and just very recently added back.  We'll track this through #93
