### ISSUE TITLE
GCP connector machine_type change

### ISSUE THREAD

**Issue by melatsg** [NetApp/terraform-provider-netapp-cloudmanager#128]
Hello,

The connector machine type should be a n2-standard-4 (the Cloud Manager default one) and not a n1-standard-4. This is preventing the creation of a connector inside the regions were the n1-standard-4 machines are not available such as europe-west8.

Could you change it ?

<img width="601" alt="Screenshot 2022-08-31 at 11 51 09" src="https://user-images.githubusercontent.com/71067709/187651204-a3545122-6a52-42b2-a9a5-87766b4895e9.png">

**Comment by chuyich** [comment]
[DEVOPS-5436](https://jira.ngage.netapp.com/browse/DEVOPS-5436)

**Comment by lonico** [comment]
Note that this is something you can set.
We changed the default in 22.9.0 to n2-standard-4.
