### ISSUE TITLE
IOPS variable is not applied in AWS

### ISSUE THREAD

**Issue by bryanheo** [NetApp/terraform-provider-netapp-cloudmanager#129]
Hello

We have deployed NetApp CVO through Terraform with 12000 IOPS in AWS but the IOPS variable is not applied 
I think this is Cloud Manager issue rather than Terraform (netapp-cloudmanager_cvo_aws). We have created extra aggregate with 12000 IOPS on gp3 through Cloud Manager manually but it still shows 3000 IOPS. 

Could you have a look at the issue and report Cloud Manager API development team if needed?

Terraform Enterprise Plan:
![image](https://user-images.githubusercontent.com/12592663/187888279-10e68f42-04c4-403a-808a-2f0576e0db5a.png)

Cloud Manager:
![image](https://user-images.githubusercontent.com/12592663/187897423-3c2f6c34-1c68-494e-a4c7-03d37821775e.png)

AWS EBS volumes:
![image](https://user-images.githubusercontent.com/12592663/187888563-3b779342-0795-4256-be90-6631d4bd2d0d.png)

Regards
Moon

**Comment by lonico** [comment]
This space is specifically about the Terraform provider.

Any issue with Cloud Manager should be addressed by opening a case.   This would have more wait coming from a customer.

**Comment by bryanheo** [comment]
@lonico Thank you for your update. I will create a case on NetApp support site
