### ISSUE TITLE
Expose Cloud Manager Connector Managed System Identity to perform role assignment.

### ISSUE THREAD

**Issue by cerocool1203** [NetApp/terraform-provider-netapp-cloudmanager#133]
The Managed System Identity should be exposed on the Cloud Manager Connector in Azure deployment to be able to add the role assignment. Otherwise, the deployments needs to be done in multiple phases. It sort should look like that. where the principal ID can be used aspart of the role assignment.

```json
resource "azurerm_role_assignment" "cm-role-assignment" {
  scope              = data.azurerm_subscription.current.id
  role_definition_id = azurerm_role_definition.cm-role.role_definition_resource_id
  principal_id       = netapp-cloudmanager_connector_azure.cero-occm.identity.principal_id
}
```

**Comment by lonico** [comment]
DEVOPS-5470
