### ISSUE TITLE
Add WORM configuration in CVO

### ISSUE THREAD

**Issue by melatsg** [NetApp/terraform-provider-netapp-cloudmanager#136]
Hello, would it be possible to add a WORM argument to be able to create a WORM CVO ?

**Comment by lonico** [comment]
On which cloud? AWS, Azure, GCP?

Currently, I don't see a WORM parameter in CloudManager APIs.

**Comment by melatsg** [comment]
I guess in all hyperscalers, in my case it would be GCP. 

It is possible to create it via GUI

**Comment by chuyich** [comment]
[DEVOPS-5586](https://jira.ngage.netapp.com/browse/DEVOPS-5586)

**Comment by chuyich** [comment]
Fix on 23.1.0
