### ISSUE TITLE
Error: Change enable_deduplication is not allowed

### ISSUE THREAD

**Issue by melatsg** [NetApp/terraform-provider-netapp-cloudmanager#138]
Hello, I created a volume with "enable_compression = true" but when I try to apply new code after, I get the following error:

"Error: Change enable_deduplication is not allowed"

The fact is that I am not changing it, the code for the volume remains the same with the attribute "enable_compression = true"

![Screenshot 2022-10-19 at 16 41 26](https://user-images.githubusercontent.com/71067709/196723124-e92f6fe6-6993-4254-97d5-cdc90d13bed5.png)

**Comment by lonico** [comment]
I wonder if ONTAP is automatically setting deduplication when you enable compression.

Could you try to add
```
enable_deduplication = true
```

**Comment by melatsg** [comment]
Hello, I enabled all the storage efficiency on the volume:

`enable_compression = true
 enable_thin_provisioning = true
 enable_deduplication = true`

**Comment by lonico** [comment]
Do you mean it failed with `Change enable_deduplication is not allowed` when using
```
enable_compression = true
enable_thin_provisioning = true
enable_deduplication = true
```

If it's the case, can you try with

```
enable_compression = true
enable_thin_provisioning = true
enable_deduplication = false
```

**Comment by lonico** [comment]
Yes, it seems that with ONTAP 9.10.1 even if I create the volume with everything enabled
It is not being configured properly.

Not happening with 9.11.1P3 from what I see.

**Comment by lonico** [comment]
Closing as it looks like an ONTAP issue.
