### ISSUE TITLE
CVO on GCP deployment without tiering does not work 

### ISSUE THREAD

**Issue by pablogarciaarevalo** [NetApp/terraform-provider-netapp-cloudmanager#140]
As the documentation states, the parameter capacity_tier is optional, and the default is 'cloudStorage'. However, using the option capacity_tier='NONE', it fails with the below error message:
`Error: code: 400, message: {"message":"Request contains invalid parameters.","violations":[{"path":"capacityTier","message":"must be one of [cloudStorage]. Actual: "},{"path":"tierLevel","message":"Bucket Storage Class must be one of 'standard' or 'nearline' or 'coldline'"}]}`

The Cloud Manager API works fine.

**Comment by lonico** [comment]
Do you mean the Cloud Manager UI works fine?    This is a message we receive from the Cloud Manager API.
Running with TF_LOG set to DEBUG would provide a trace.

**Comment by pablogarciaarevalo** [comment]
Cloud Manager UI and Cloud Manager API call (https://docs.netapp.com/us-en/cloud-manager-automation/cm/wf_gcp_cloud_create_we_paygo.html#8-create-the-working-environment) work fine. See attached the TF log.
[TF_log.txt](https://github.com/NetApp/terraform-provider-netapp-cloudmanager/files/9885468/TF_log.txt)

**Comment by chuyich** [comment]
Raised DEVOPS-5622 for tracking this issue.

**Comment by chuyich** [comment]
22.11.0
