### ISSUE TITLE
Error: InvalidParameterValue: Value (OCCM_AUTOMATION) for parameter iamInstanceProfile.name is invalid.

### ISSUE THREAD

**Issue by pl1ght** [NetApp/terraform-provider-netapp-cloudmanager#15]
AWS -Creating Cloud Connector- I have successfully generated Cloud.netapp.com refresh token, created AWS IAM Role/Policies, kept default naming convention of OCCM_AUTOMATION.  Definitely getting to AWS as it validates my VPC and SGs, but fails when trying to find the IAM Policy OCCM_AUTOMATION with Error: InvalidParameterValue: Value (OCCM_AUTOMATION) for parameter iamInstanceProfile.name is invalid.  I am aware there is a time frame after creating AWS Policy before it may show active, but it has been 12 hours.   Terraform apply bombs out after inserting refresh token and saying Yes that it can't find the above IAM Policy.  Hopefully just doing something dumb.  I can aws iam list-policies to validate that my policy does exist.

**Comment by pl1ght** [comment]
> 
> 
> AWS -Creating Cloud Connector- I have successfully generated Cloud.netapp.com refresh token, created AWS IAM Role/Policies, kept default naming convention of OCCM_AUTOMATION. Definitely getting to AWS as it validates my VPC and SGs, but fails when trying to find the IAM Policy OCCM_AUTOMATION with Error: InvalidParameterValue: Value (OCCM_AUTOMATION) for parameter iamInstanceProfile.name is invalid. I am aware there is a time frame after creating AWS Policy before it may show active, but it has been 12 hours. Terraform apply bombs out after inserting refresh token and saying Yes that it can't find the above IAM Policy. Hopefully just doing something dumb. I can aws iam list-policies to validate that my policy does exist.

resource "netapp-cloudmanager_connector_aws" "cl-occm-aws" {
  provider = netapp-cloudmanager
  name = "TF-ConnectorAWS"
  region = "us-east-1"
  key_name = "automation_key"
  company = "NetApp"
  instance_type = "t3.xlarge"
  subnet_id = "subnet-XXXXXXX"
  security_group_id = "sg-XXXXX"
  iam_instance_profile_name = "OCCM_AUTOMATION"
  account_id = "account-XXXXX"

**Comment by edarzi** [comment]
Did you create policy and role which use that policy?
You should provide the name of the role

**Comment by pl1ght** [comment]
Yes, created IAM policy, in AWS using cloud manager example, attached EC2 role to that policy.  Is there a var in that config to add the role as well?  I worked off of the default example just to validate auth/aws side was correct.   If there is a more indepth documenation on this I would be happy to dig in further.  Appreciate the quick response.

**Comment by edarzi** [comment]
And the name of the role is OCCM_AUTOMATION?
________________________________

**Comment by pl1ght** [comment]
yes,correct.  I just used all of the example configs defaults in my AWS account IAM roles.

**Comment by avivdeg** [comment]
Here is the direct link to the relevant policies:
https://mysupport.netapp.com/site/info/cloud-manager-policies

**Comment by edarzi** [comment]
Just to verify the required steps:
1. create policy with the following permissions: https://occm-sample-policies.s3.amazonaws.com/Policy_for_Cloud_Manager_3.8.7.json (names it: OCCM_AUTOMATION )
2. Create role of type ec2 which used the created policy (OCCM_AUTOMATION) from the previous step and name it also: OCCM_AUTOMATION

**Comment by pl1ght** [comment]
Cheers!  I had missed one role, looking good now.  Thank you for the very quick responses folks!
