### ISSUE TITLE
GCP Key rotation recreates NetApp connector and CVO 

### ISSUE THREAD

**Issue by bryanheo** [NetApp/terraform-provider-netapp-cloudmanager#153]
Hello

The Key rotation of the GCP service account has been recently suggested by our security team and we trying to use the key rotation as below but it recreates NetApp connector and CVO. Are there any way to rotate the service account without replacing the existing Connector and CVO? 

Code Change:
![image](https://user-images.githubusercontent.com/12592663/222178082-be4cb1a7-2741-4205-8cb3-ca24e19125cc.png)

Terraform Plan:
![image](https://user-images.githubusercontent.com/12592663/222178404-7f6bb97d-b9fb-491c-b36a-0d54141e087c.png)

Regards
Moon

**Comment by chuyich** [comment]
Using lifecycle with ignore_changes may help your case. Terraform will ignore the key change and it won't recreate the resoruce.
Here is an example (assume you are using **service_account_key**:
resource "netapp-cloudmanager_connector_gcp" "cl-occm-gcp" {
  provider = netapp-cloudmanager  
  :
  service_account_key = "xxxx"
  :
  **lifecycle {
    ignore_changes = [
      service_account_key,
    ]
  }**
}

**Comment by bryanheo** [comment]
@chuyich Thank you for your comment.
If we ignore the change and the key is rotated, does connector works ok?
I am worried of that the connector does not work due to the key rotation.

**Comment by chuyich** [comment]
@bryanheo With this way, it will be a risk that the state file is out of sync since it records the key in the state file. Although it is set to be ignored the change, we will propose a better solution with the adjustment on the key parameter on our side. Will keep updating you if the change is available.

**Comment by chuyich** [comment]
@bryanheo Did you have a chance to try it? Can we close this? We will close this by the end of this week if we don't hear anything from you.

**Comment by bryanheo** [comment]
@chuyich Thank you for the update
Our current version is 22.2.1 and TFE plan shows the connector and cvo are recreated with 23.5.1 version so we are investigating it
![image](https://github.com/NetApp/terraform-provider-netapp-cloudmanager/assets/12592663/09fe87ce-b58e-424d-9a33-155a19b760ce)

**Comment by chuyich** [comment]
@bryanheo Thanks for the update. Yes. Please use 23.5.1. If you do the plan and see the service_account_key is changed, it's normal cause the different key needs to be reflected on the terraform state file. So the setup on state file will be on the same as reality. But after you do the apply, it should not destroy the existing GCP connector and create a new one. Only the service_account_key will be updated in the state file.
Let us know if you see anything special.

**Comment by chuyich** [comment]
It's been over one month with no update from the user. Please raise a new one if it's needed.
