### ISSUE TITLE
TF Registry Documentation Links to Azure Policy/Role definitions are outdated

### ISSUE THREAD

**Issue by dismn8r** [NetApp/terraform-provider-netapp-cloudmanager#155]
The NetApp Terraform Provider documentation page https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/latest/docs/resources/connector_azure contains outdated links to the policies required for creating a connector and for attaching to the connector to deploy CVO.

[Connector deployment policy for Azure](https://s3.amazonaws.com/occm-sample-policies/Policy_for_Setup_As_Service_Azure.json) is currently correct/identical but should probably refer to the documented policy definition at ...
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html#set-up-permissions-for-your-azure-account

[Cloud Manager policy for Azure](https://occm-sample-policies.s3.amazonaws.com/Policy_for_cloud_Manager_Azure_3.8.7.json) is incorrect and should refer to ...
https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions-azure.html#custom-role-permissions

These outdated links hosted at https://s3.amazonaws.com/occm-sample-policies/  should be removed from public view if they aren't going to be updated, or aren't the source of truth.

**Comment by chuyich** [comment]
Raised DEVOPS-5964 to track this.

**Comment by chuyich** [comment]
Fixed on 23.3.2
