### ISSUE TITLE
Unable to disable Tiering via Terraform in GCP

### ISSUE THREAD

**Issue by venukntap** [NetApp/terraform-provider-netapp-cloudmanager#157]
Hi Team,

We are trying to deploy a CVO instance with Tiering disabled in GCP.
Previously Laurent advised to remove the below two variables to disable the Tiering. By doing so, it is still taking the tier_level as standard. Can you please let us know how do deploy a CVO instance without tiering?

[capacity_tier](https://registry.terraform.io/#capacity_tier) - (Optional) Indicates the type of data tiering to use: ['cloudStorage']. The default is 'cloudStorage'.
[tier_level](https://registry.terraform.io/#tier_level) - (Optional) In case capacity_tier is cloudStorage, this argument indicates the tiering level: ['standard', 'nearline', 'coldline']. The default is: 'standard'.

Regards,
Venu

**Comment by chuyich** [comment]
This issue has been taken care in the email. Close it.
