### ISSUE TITLE
code 504 cloud_connector & cvo_svm terraform destroy bug

### ISSUE THREAD

**Issue by lomar92** [NetApp/terraform-provider-netapp-cloudmanager#158]
terraform ressources for cloud_connector can and svm can not be destroyed. sometimes it destroys the cvo_svm in aws successfull but destroy process stops immidiately with code 504 and I can not do a terraform destroy again. Cloud conncetor can not be found / working environment id not available even though the cloud connector is still there. Therefore all my other ressources I am deploying together with cvo ontap can not be destroyed due to this error and I have to manually delete them on the aws management console. 

![image](https://user-images.githubusercontent.com/53077361/225694491-d922abc2-2434-4290-9249-35d4109d8c7b.png)

**Comment by wenjun666** [comment]
I understand you are trying to delete a series of resources. What is the sequence of the actions will get you the above 504?

**Comment by lomar92** [comment]
terraform destroy after a succesfull apply. not sure what you mean, but the ressources are still there when look on the aws management console.....
![Bildschirm­foto 2023-03-18 um 19 43 59](https://user-images.githubusercontent.com/53077361/226129840-73ec2617-6d2e-4103-9d07-e6038c960f5f.png)

![image](https://user-images.githubusercontent.com/53077361/226129726-b4d1d87e-8eab-4ec9-b20d-9fe1e1a4ddc6.png)

**Comment by wenjun666** [comment]
okay, the OCCM and CVO are created successfully. After that, when you do terraform destroy, is the destroy successful or fail? Or the first destroy runs through, and get the above error on the second attempt to destroy?

**Comment by lomar92** [comment]
Both. First and second attempt fails.

**Comment by wenjun666** [comment]
Can you please share the tf code so I can try to reproduce?

**Comment by lomar92** [comment]
Sure. Here is the code Snippet: 
https://gist.github.com/lomar92/0d369a618bc2c474c24fa02b59167836

**Comment by wenjun666** [comment]
I was able to create an aws connector and cvo in the same resource and destroy successfully.
```
resource "netapp-cloudmanager_connector_aws" "cm-aws" {
  provider = netapp-cloudmanager
  name = "TerraformTest”
  region = "us-west-1"
  company = "NetApp"
  key_name = "dev_xxx”
  instance_type = "t3.xlarge"
  subnet_id = "subnet-xxx”
  security_group_id = "sg-xxx”
  iam_instance_profile_name = “xxxx”
  associate_public_ip_address = true
  account_id = "account-xxx”

}

resource "netapp-cloudmanager_cvo_aws" "cvo-aws" {
 provider = netapp-cloudmanager
 name = "TerraformCVO3"
 region = "us-west-1"
 subnet_id = "subnet-xxx”
 vpc_id = "vpc-xxx”
 svm_password = “xxx”
 client_id = netapp-cloudmanager_connector_aws.cm-aws.client_id
 writing_speed_state = "NORMAL"
}
```

**Comment by wenjun666** [comment]
Please reopen this issue if issue remains
