### ISSUE TITLE
How to configure Linux/Unix UID and GID in volumes?

### ISSUE THREAD

**Issue by AndresPineros** [NetApp/terraform-provider-netapp-cloudmanager#162]
As the title says, is there a way to configure these attributes in the volumes?

**Comment by chuyich** [comment]
@AndresPineros Can you share more details about your use case? What do you plan to do?

**Comment by chuyich** [comment]
There is no response from the requester more than 2 weeks. Close this for now. Please raise another ticket with the details if this needs to be supported.
