### ISSUE TITLE
Terraform Destroy is Failing with Diff Error Messages Every time (Azure)

### ISSUE THREAD

**Issue by vijaysaladi** [NetApp/terraform-provider-netapp-cloudmanager#165]
I am trying to destroy, Netapp CVO and connector using terraform destroy command. But every time it is failing with diff error messages.

Once I am getting this error. But I am using the same latest Azure bluexp role for creating instances. But failing during destroy. But getting succussed in the next run.

_"**Error: failed to delete CVO, error: You don't have permission to perform this action. For more information please refer to the OnCommand Cloud Manager policies documentation at https://mysupport.netapp.com/site/info/cloud-manager-policies**"__

Once it is deleting the CVO vm's but not its related data disks.

Sometimes it is failing to delete the connector VM data disks.

Seems like the dependencies are not setup properly during deletion.

**Comment by vijaysaladi** [comment]
![image](https://github.com/NetApp/terraform-provider-netapp-cloudmanager/assets/107714272/f209feaf-947b-4628-90da-65cb7bd6a001)
![image](https://github.com/NetApp/terraform-provider-netapp-cloudmanager/assets/107714272/5fa225ef-9dca-44dc-930c-a39b84bf8d35)

**Comment by chuyich** [comment]
Would you please check if the account has needed permission? https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions-azure.html#custom-role-permissions

**Comment by vijaysaladi** [comment]
I am using the latest custom role permissions. 

Just to add every time, I am getting different error messages. But it is failing to perform clean destroy. Some components are missing to be deleted.

**Comment by chuyich** [comment]
As I know it requires more in the role permission than before. That's why we suggest you to compare the document and double check if any permission is missing on your side. For the first error message, you may to go to AZURE to delete the lock and try it again. If it's not the case right now, what error message do you have?

**Comment by chuyich** [comment]
@vijaysaladi It's been over one month and we didn't hear from you. Please raise a new one if you still have this issue.
