### ISSUE TITLE
GCP HA now supports fast write mode

### ISSUE THREAD

**Issue by nichollri** [NetApp/terraform-provider-netapp-cloudmanager#170]
Currently we get an error when setting writing_speed_state to HIGH for deploying CVO HA pair in GCP with this setting.
This feature came into BlueXP / ONTAP 9.13.0
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#flash-cache-and-high-write-speed-in-google-cloud
This should be supported in Terraform deployments.

**Comment by chuyich** [comment]
The fix has been delivered in the new release 23.6.1 yesterday

**Comment by nichollri** [comment]
Thank you!!!
