### ISSUE TITLE
AWS - not supported in By Node Base charging method

### ISSUE THREAD

**Issue by samh241** [NetApp/terraform-provider-netapp-cloudmanager#199]
Hi, Im getting the following error when applying the plan.

```
Error: code: 400, message: {"message":"Subscription with id aws-XXXXXX is not supported in By Node Base charging method","causeMessage":"BadRequestException: Subscription with id aws-XXXXXXis not supported in By Node Base charging method"}

  on .terraform/modules/cvo2/aws/netapp_cloudmanager_cvo_aws/main.tf line 1, in resource "netapp-cloudmanager_cvo_aws" "cvo_aws":
   1: resource "netapp-cloudmanager_cvo_aws" "cvo_aws" {


Error: Terraform command exited with exit code: 1
```

Im using the following variable’s 

```
cvo2_name                   = "netapp-cvo2"
cvo_instance_type           = "m5.xlarge"
cvo_license_type            = "cot-explore-paygo"
capacity_package_name       = "Essential"
ontap_version               = "ONTAP-9.15.0P1.T1"
cvo_is_ha                   = false
connector_account_access_id = "CloudProviderAccount-JLHkoJXC"
```

There seems to be a problem between the NetApp Provider (24.5.0) and the NetApp BlueXP subscription in AWS Market place, product ID
e83af128-0aa6-478e-8c9c-39ce6702e1f8

**Comment by chuyich** [comment]
Ref. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#how-to-get-started-2 
Node-based licensing
Node-based licensing is the previous generation licensing model that enabled you to license Cloud Volumes ONTAP by node. This licensing model is not available for new customers and no free trials are available. By-node charging has been replaced with the by-capacity charging methods described above.

Node-based licensing is still available for existing customers:

If you have an active license, BYOL is available for license renewals only.

If you have an active marketplace subscription, charging is still available through that subscription.

**Comment by chuyich** [comment]
@samh241 Can we close this issue?

**Comment by chuyich** [comment]
Close this issue since it's been two weeks and no response.
