### ISSUE TITLE
CVO-HA Azure deployment failure using terrafom providers

### ISSUE THREAD

**Issue by a127608** [NetApp/terraform-provider-netapp-cloudmanager#21]
While deploying CVO-HA instance using terraform provider in azure getting below “az login” error 

Appreciate someone could help us to understand if we are missing something here
==============================
Error: Invoking Azure CLI failed with the following error: Please run 'az login' to setup account.
 on cvo.tf line 1, in resource "netapp-cloudmanager_cvo_azure" "cvo_ha":
   1: resource "netapp-cloudmanager_cvo_azure" "cvo_ha" 

===================

**Comment by edarzi** [comment]
you need to do az login before using the provider so it will be able to create the required resources

From the documentation:
Provides a netapp-cloudmanager_connector_azure resource. This can be used to create a new Cloud Manager Connector in AZURE. The environment needs to be configured with the proper credentials before it can be used (az login). The minimum required policy can be found at Connector deployment policy for Azure (https://s3.amazonaws.com/occm-sample-policies/Policy_for_Setup_As_Service_Azure.json)

**Comment by a127608** [comment]
We are using CI/CD pipeline with terraform workspace which is already connected to subscription. Same pipeline has no issues for deploying VMs using azurerm providers.
