### ISSUE TITLE
Deploying CVO to an existing Resource group in Azure is getting ignored

### ISSUE THREAD

**Issue by psaha3** [NetApp/terraform-provider-netapp-cloudmanager#22]
Tried specifying an existing RG with the resource_group parameter but it is ignoring this and creating a new RG. Understand that deploying CVO to an existing RG is not recommended - however, we have a dedicated RG for CVO components which is our requirement. Has anyone deployed CVO in an existing RG before - please share your views.

**Comment by edarzi** [comment]
Hi, currently not supported in the provider. We can add it easily if required

**Comment by psaha3** [comment]
Thanks @edarzi , how can we add it?

**Comment by edarzi** [comment]
It required code change, will add that option to the provider.
I assume can be available in the next update, will let you know

**Comment by psaha3** [comment]
ok great. Thanks @edarzi

**Comment by edarzi** [comment]
Will be available in the next publish -  next week

**Comment by edarzi** [comment]
Option available in 21.1.0 version

**Comment by lonico** [comment]
fixed with 33147ac0f1d8e1852a963c28238606fbe11d1fd8
