### ISSUE TITLE
Unable to remove resources with Terraform destroy

### ISSUE THREAD

**Issue by watsonjm** [NetApp/terraform-provider-netapp-cloudmanager#33]
Hello, when creating an HA pair, the instances for node1, node2, and the mediator all have termination protection on them. Would it be possible to get a variable to control this?

**Comment by edarzi** [comment]
Actually no, it is part of the creation. It is possible to control it on the connector.
It is recommended to delete via Cloud Manger (or Terraform) and not directly on AWS console
