### ISSUE TITLE
capacityTier accepts "none" as valid entry, but creation fails because "none" isn't referenced in the if statement

### ISSUE THREAD

**Issue by felix-melligan** [NetApp/terraform-provider-netapp-cloudmanager#34]
https://github.com/NetApp/terraform-provider-netapp-cloudmanager/blob/266364056e52ed3da73939d6019f2d4ba0a576d6/cloudmanager/resource_netapp_cloudmanager_snapmirror.go#L129

netapp-cloudmanager_cvo_gcp.cl-cvo-gcp: Refreshing state... [id=vsaworkingenvironment-3r3ljrnd]
netapp-cloudmanager_volume.cvo-volume-source: Refreshing state... [id=b2abcd64-76c0-11eb-93c7-4981710572cf]
 
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 
Terraform will perform the following actions:
 
  # netapp-cloudmanager_snapmirror.cl-snapmirror will be created
  + resource "netapp-cloudmanager_snapmirror" "cl-snapmirror" {
      + capacity_tier                      = "none"
      + client_id                          = "DIIfQ0VYmWZNHuUloTNTo4jaAuIdgdsp"
      + destination_aggregate_name         = "aggr1"
      + destination_svm_name               = "svm_gcpreplnetapp"
      + destination_volume_name            = "tgt_vol1"
      + destination_working_environment_id = "vsaworkingenvironment-msywnwae"
      + id                                 = (known after apply)
      + max_transfer_rate                  = 102400
      + policy                             = "MirrorAllSnapshots"
      + schedule                           = "5min"
      + source_svm_name                    = "svm_terraformreplsrc"
      + source_volume_name                 = "src_vol1"
      + source_working_environment_id      = "vsaworkingenvironment-3r3ljrnd"
    }
 
Plan: 1 to add, 0 to change, 0 to destroy.
 
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
 
  Enter a value: yes
 
netapp-cloudmanager_snapmirror.cl-snapmirror: Creating...
 
Error: code: 400, message: {"message":"Request contains invalid parameters.","violations":[{"path":"capacityTier","message":"must be one of [S3, Blob, cloudStorage]. Actual: none"}]}
 
  on CVO_terraform.tf line 54, in resource "netapp-cloudmanager_snapmirror" "cl-snapmirror":
  54: resource "netapp-cloudmanager_snapmirror" "cl-snapmirror" {

**Comment by lonico** [comment]
The expectation is that you would not set capacity_tier if you want to use a default value.
But yes, we should not allow 'none' as a choice.
We'll address this.

**Comment by lonico** [comment]
fixed in 1094c714a6271ebe82af95ede5ea8fc66701e8f4
