### ISSUE TITLE
data_encryption_type for custom encryption

### ISSUE THREAD

**Issue by vijaymailb** [NetApp/terraform-provider-netapp-cloudmanager#35]
"data_encryption_type" argument missing in provider to pass own custom encryption key in TF file.

**Comment by edarzi** [comment]
will be added, on which Cloud Provider are you working?

**Comment by vijaymailb** [comment]
Thanks. We use GCP.

**Comment by lonico** [comment]
fixed with 1094c714a6271ebe82af95ede5ea8fc66701e8f4
