### ISSUE TITLE
Cloud backup API argument missing

### ISSUE THREAD

**Issue by vijaymailb** [NetApp/terraform-provider-netapp-cloudmanager#36]
Cloud backup API argument missing in cloud manager terraform provider.

**Comment by lonico** [comment]
Could you tell us which argument is missing?

**Comment by lonico** [comment]
We checked with the CloudManager team, and they did not implement the Cloud backup APIs yet.  There is no plan for this at this time.

**Comment by vijaymailb** [comment]
Thank you for the update.
