### ISSUE TITLE
netapp-cloudmanager_cvo_aws: mediator_assign_public_ip is ignored (not sent in API request)

### ISSUE THREAD

**Issue by dmccaffery** [NetApp/terraform-provider-netapp-cloudmanager#40]
When the `MediatorAssignPublicIP` value is set to false (default value for a bool value type in golang), the struct tag with omitempty does not include the boolean in the request. The default value server-side appears to be true, which currently makes it impossible to create a mediator without assigning a public IP.

**Comment by jorgeedugona** [comment]
Hi Team, 
Is there a fix for this? Assigning a public IP to the mediator is not an option for some people. 
Kind Regards
Jorge

**Comment by lonico** [comment]
As indicated by Justin, this was fixed 25 days ago.  This was published in The Terraform Registry as 21.4.0.
Note that we just published a 21.5.0 yesterday.
