### ISSUE TITLE
No argument/resource reference to create workspace in cloud manager

### ISSUE THREAD

**Issue by vijaymailb** [NetApp/terraform-provider-netapp-cloudmanager#42]
Hi Team,

We need to create multiple workspace for different environments. Is it possible to include workspace(tenant) resource in provider?

**Comment by edarzi** [comment]
Hi

Workspace is on the account level, you can create it once and it not associated to the connector. all connectors in the account will see the workspaces. create it once from the UI and use it in the calls

**Comment by lonico** [comment]
@edarzi Do we have some document that explains this?  We could point to it in our documentation.
