### ISSUE TITLE
add support for darwin/arm64 (apple silicon)

### ISSUE THREAD

**Issue by dmccaffery** [NetApp/terraform-provider-netapp-cloudmanager#43]
The provider does not currently publish a build with support for Apple silicon. Support for this should be added as terraform now officially supports this and has updated all of their providers.

**Comment by dmccaffery** [comment]
I built and tested locally and it works just fine without any code changes when building with go 1.16 (where support was added).

I don't see any pipeline/publish process in this repo so I can't help implement what is required. It may be a simple upgrade to go 1.16 on the build agent / within the build process as it appears that all other GOOS/GOARCH platforms are built and published, so I'm assuming that's done via lookup -- but maybe not.

Let me know if I can be of any assistance. Thanks!

**Comment by wenjun666** [comment]
Thanks for the comment, the next release will support darwin/arm64.
