### ISSUE TITLE
Terraform assumes ALL VPCs are shared when using shared VPC for VPC 0 in GCP

### ISSUE THREAD

**Issue by felix-melligan** [NetApp/terraform-provider-netapp-cloudmanager#51]
When setting the network_project_id in the netapp-cloudmanager_cvo_gcp resource, terraform uses that same network_project_id for all of the VPC paths, not just the path for VPC 0. This means that if we want to use a VPC residing in project_id project, we cannot. 

**Current behavior:**

VPC0: Shared VPC using network_project_id
VPC1: Private VPC using project_id
VPC2: Private VPC using project_id
VPC3: Private VPC using project_id

Path on API call for this should be:
VPC0: projects/[network_project_id]/global/networks/[vpc0_node_and_data_connectivity]
VPC1: projects/[network_project_id]/global/networks/[vpc1_cluster_connectivity]
VPC2: projects/[network_project_id]/global/networks/[vpc2_ha_connectivity]
VPC3: projects/[network_project_id]/global/networks/[vpc3_data_replication]

**Desired behavior:**

VPC0: Shared VPC using network_project_id
VPC1: Private VPC using project_id
VPC2: Private VPC using project_id
VPC3: Private VPC using project_id

Path on API call for this should be:
VPC0: projects/[network_project_id]/global/networks/[vpc0_node_and_data_connectivity]
VPC1: projects/[project_id]/global/networks/[vpc1_cluster_connectivity]
VPC2: projects/[project_id]/global/networks/[vpc2_ha_connectivity]
VPC3: projects/[project_id]/global/networks/[vpc3_data_replication]

Similarly, the subnet paths need to be updated in line with the VPC paths

**Comment by edarzi** [comment]
Hi
That assumption was based on Cloud Manger usage, we checked that with the dev team and the decision was to make it like that.
Will check with the team what can be done and let you know

**Comment by felix-melligan** [comment]
@edarzi thankyou - this is a very common configuration seen by _most_ CVO HA deployments in GCP so it would be great to have it intergrated. Thanks!

**Comment by lonico** [comment]
fixed in v21.7.0
