### ISSUE TITLE
netapp-cloudmanager_cifs_server.AWS-cifs Error

### ISSUE THREAD

**Issue by jorgeedugona** [NetApp/terraform-provider-netapp-cloudmanager#52]
when netapp_cloudmanager_cifs_server is used I encountered the below error: 

netapp-cloudmanager_cifs_server.AWS-cifs: Creating...

Error: Provider produced inconsistent result after apply

When applying changes to netapp-cloudmanager_cifs_server.AWS-cifs, provider
"registry.terraform.io/netapp/netapp-cloudmanager" produced an unexpected new
value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by jorgeedugona** [comment]
Terraform v0.14.10
+ provider registry.terraform.io/netapp/netapp-cloudmanager v21.5.3

**Comment by lonico** [comment]
We were not correctly reporting the error.

fixed in a46401d67704dc50cddb597beff92263fe59d1da

released as 21.6.0
