### ISSUE TITLE
Encrypt EBS disks with AWS KMS for Cloud Manager and Cloud Volumes ONTAP

### ISSUE THREAD

**Issue by felix-melligan** [NetApp/terraform-provider-netapp-cloudmanager#54]
Would like the option to provide:
"aws_encryption": {
   "kms_key_arn": "string",
   "kms_key_id": "string"
}

and pass that through to AWS to create the cloud manager instance with EBS disks encrypted by that key defined as well as the ability to then pass that key as a variable whilst deploying CVO in AWS to encrypt all of the EBS disks as well.

Currently, this would be available via the Cloud Manager API:
https://docs.netapp.com/us-en/occm/api.html#_awsencryption

**Comment by lonico** [comment]
These are two different requests.   We're looking at the second one as there is an API to support it.   And investigating the feasibility of the first request.

**Comment by lonico** [comment]
fixed in 3c873130cdf555df2ab7d596379607debebe7db5
published as 21.8.0
