### ISSUE TITLE
firewall_tags in netapp-cloudmanager_connector_gcp should allow you to specify tags

### ISSUE THREAD

**Issue by felix-melligan** [NetApp/terraform-provider-netapp-cloudmanager#59]
Currently, there is no way to apply your own firewalls to the connector instance that you deploy.

I propose that the "firewall_tags" variable enables you to specify an array of tags that you wish to apply to the instance. This would enable you to use pre-defined firewalls that are created before deploying the CM instance.

This would require another boolean which would be "let_cloudmanager_create_firewall".

Currently, you would have to deploy the instance, add it to GCP terraform and then apply the tags manually

**Comment by lonico** [comment]
current firewall_tags is a boolean, and triggers the creation of fixed values

```
	if occmDetails.FirewallTags == true {
		t.Properties.Tags.Items = []string{"firewall-tag-bvsu", "http-server", "https-server"}
	}
```

Would a new CustomFirewallTags property that takes a list of strings satisfy this request?

**Comment by felix-melligan** [comment]
Yes - I think that this would indeed fix the issue in the short term. The REST APIs likely need to be updated so that they can also accept tags rather than "firewall rules" as well. Thanks!

**Comment by felix-melligan** [comment]
Just seen that no firewall_rule parameter is allowed for this resource either, so you can't use your own pre-made firewalls

**Comment by carchi8py** [comment]
This has been released.
