### ISSUE TITLE
Documentation needs example of CVO HA in GCP to show self-links

### ISSUE THREAD

**Issue by felix-melligan** [NetApp/terraform-provider-netapp-cloudmanager#61]
Currently self-links aren't explained fully in the documentation to show how to reference them inside the provider or where to get them from Google (You cannot get them from the console, only gcloud commands, or you have to build the path yourself).

Worth entering an example:
A self link for a VPC looks like this: 
https://www.googleapis.com/compute/v1/projects/[project]/global/networks/[network_name]

An example would be:
https://www.googleapis.com/compute/v1/projects/my-project/global/networks/default

A self link for a subnet looks like this: https://www.googleapis.com/compute/v1/projects/[project]/regions/[region]/subnetworks/[subnet_name]

An example would be:
https://www.googleapis.com/compute/v1/projects/my-project/regions/us-east4/subnetworks/default

**Comment by edarzi** [comment]
Hi 

Please use the following format:
For vpc
projects/netapp-test/global/networks/vpc1-netapp-test"

For  subnet 
"projects/netapp-test/regions/europe-west1/subnetworks/vpc1-netapp-test"

  We will update the documentation with the samples

**Comment by chuyich** [comment]
GCP HA example has been added as part of DEVOPS-6308 and released on version 23.6.1
