### ISSUE TITLE
[v21.8.1] AWS Connector reads only first security group.

### ISSUE THREAD

**Issue by MindBreakerVictor** [NetApp/terraform-provider-netapp-cloudmanager#65]
Hello,

The recently released version, 21.8.1, has a bug in reading the AWS connector, setting only the first SG in the security_group_id property for the createOCCMDetails object.
[Line 277 of cloudmanager/resource_netapp_cloudmanager_connector_aws.go](https://github.com/NetApp/terraform-provider-netapp-cloudmanager/compare/v21.8.0...v21.8.1#diff-0a1cf92f2b3d681591bd714b352c87742330a3e0de45ef64a8a3fb2a9f047b02R277)
The value must be a comma-delimited list of security group ids associated with the connector EC2 instance.
This causes resource recreation which cascades down to entire CVO environments being recreated when more than one security group is used.

**Comment by MindBreakerVictor** [comment]
@wenjun666 please take a look at this as this is a breaking change.

**Comment by wenjun666** [comment]
@MindBreakerVictor Thank you for raising the issue, fixing it right now.

**Comment by lonico** [comment]
fixed in 072ac5cca0c3befe4200e9630044e6f5a6a0904a
published as 21.9.0
