### ISSUE TITLE
Resource Group created with the CVO in Azure

### ISSUE THREAD

**Issue by davetustin** [NetApp/terraform-provider-netapp-cloudmanager#69]
Hi,

When creating a CVO with netapp-cloudmanager_cvo_azure the resource group is created at the same time. If you want to use an existing resource group, this is not possible and Terraform stops due to the group already existing.

If this could be changed so the resource group can be built outside of the CVO and use that group for the resources, that would be great!

Thanks

**Comment by edarzi** [comment]
Hi

that is possible by adding the "allow_deploy_in_existing_rg" parameter in the azure cvo creation.
take a look in the documentation.

**Comment by davetustin** [comment]
Hi @edarzi 

Thank you! I am still getting used to this provider, I should have seen that.

Thanks for your help!
Dave
