### ISSUE TITLE
The associate_public_ip_address creates a public IP even when set to false

### ISSUE THREAD

**Issue by davetustin** [NetApp/terraform-provider-netapp-cloudmanager#70]
Hi,

When `associate_public_ip_address = false` is configured with `netapp-cloudmanager_connector_azure`, the public ip resource is created and associated with the virtual machine nic.

For the time being, I am removing the public ip manually after creation.

Thank you as always!
Dave

**Comment by wenjun666** [comment]
The issue is now fix with v21.9.4.
