### ISSUE TITLE
RFE - Support capacity licensing within provider

### ISSUE THREAD

**Issue by felix-melligan** [NetApp/terraform-provider-netapp-cloudmanager#72]
Current license types only include BYOL and PAYGO, but we need additional support for capacity packages (and freemium).

Would need:
additional license_type: capacity-paygo
additional parameter: capacity_package_name: essential/freemium/professional

**Comment by lonico** [comment]
Yes, we are working on adding capacity licenses and the new parameter.

**Comment by felix-melligan** [comment]
Thanks!

**Comment by lonico** [comment]
fixed by 2da50efe47b765bd628924a76d836dd4bd58e6a1
published as 21.9.4 on Terraform Registry
