### ISSUE TITLE
Unexpected SHA-256 hash for `21.9.2` release

### ISSUE THREAD

**Issue by radeksimko** [NetApp/terraform-provider-netapp-cloudmanager#74]
It appears that the latest release published in the official Registry (5 days ago) doesn't match with what was just published here on GitHub (1 hour ago).

 - https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/latest
 - https://github.com/NetApp/terraform-provider-netapp-cloudmanager/releases/tag/v21.9.2

This can be reproduced with `terraform init` and corresponding `required_providers` entry which results in the following

```
Error: Failed to install provider

Error while installing netapp/netapp-cloudmanager v21.9.2: checksum list has
unexpected SHA-256 hash
d64332f424f8de615f347277c70532141aa0e4314250e557942c102c1cab40cc (expected
ecbeadad5b629628301a14da48c2f1b7242e00d26ff54ae278d562702dfd92a9)
```

**Comment by wenjun666** [comment]
Hi @radeksimko , I deleted the old v21.9.2 and release a new version of v21.9.2. The terraform registry seems picked up the change(the doc is updated), but the release time is never updated as you indicate. By any chance, do you have a idea on how to fix this?

**Comment by radeksimko** [comment]
Generally speaking releases should be treated as immutable, i.e. you shouldn't really be deleting releases. I'm not sure if the Registry has a way of marking old releases in some way, but I imagine that such mechanism would only be relevant if that release has a significant vulnerability or is broken for most users, i.e. presents a high enough risk that warrants such action.

Do you mind sharing the reason for deletion of the old version?

Either way I would recommend cutting a new patch version (`21.9.3`).

**Comment by wenjun666** [comment]
I am okay with publishing a new patch version. But is there a way to fix 21.9.2 so that it's not in broken state? Should I replace it with the old version?

**Comment by radeksimko** [comment]
If you have the original old release assets and can re-upload the assets to GitHub under the same version then yes - I _think_ that might fix it - alternatively/additionally I'd advise you contacting the TF Registry team on terraform-registry@hashicorp.com as they are better equipped to answer such questions

**Comment by wenjun666** [comment]
Replace with the old version of 21.9.2 and it works fine.
