### ISSUE TITLE
OCCM Agent taking to long when creating the Cloud Connector

### ISSUE THREAD

**Issue by davetustin** [NetApp/terraform-provider-netapp-cloudmanager#78]
Hi all,

Only recently I have started having issues deploying a Cloud Connector using the  latest version of the provider (21.9.4). After about 17mins the following error occurs in the console.

```
Error: Taking too long for OCCM agent to be active or not properly setup

  with netapp-cloudmanager_connector_azure.this,
  on cloud-connector.tf line 8, in resource "netapp-cloudmanager_connector_azure" "this":
   8: resource "netapp-cloudmanager_connector_azure" "this" {
```

I have had it deploy in the past with no issues.

Is anyone else having this problem or could it be my environment causing it?

Many thanks
Dave

**Comment by lonico** [comment]
That generally means that the VM was successfully created, but the agent status stays in "pending" forever.

It could be a discrepancy in permissions between Azure and CloudManager.   Make sure the credentials match.

@edarzi   We'll need some help from CloudManager team to understand why the registration does not complete.

**Comment by carchi8py** [comment]
We increased the timeout time. Please let us know if this is still an issue.
