### ISSUE TITLE
Update data_floating_ips and svm_floating_ip for netapp-cloudmanager_cvo_aws

### ISSUE THREAD

**Issue by alikulov** [NetApp/terraform-provider-netapp-cloudmanager#79]
Hi.
Changes of `data_floating_ip, data_floating_ip2, svm_floating_ip` forces recreation of `netapp-cloudmanager_cvo_aws`. At the same time, it's possible to change data_lifs addresses via ONTAP CLI, Cloud Manager fetches these updated addresses and shows them in web UI. There are also no issues with mediator updating routing tables in AWS with new addresses automatically.
It would be convenient to change floating IPs change via terraform.
As a workaround, I've tried to edit floating IP addresses in a state file but looks like there is some metadata that is not updated when one changes data_lifs addresses in ONTAP CLI.
```
   # netapp-cloudmanager_cvo_aws.netapp-cvo must be replaced
 -/+ resource "netapp-cloudmanager_cvo_aws" "netapp-cvo" {
       ~ data_floating_ip              = "192.168.87.1" -> "192.168.87.51" # forces replacement
       ~ data_floating_ip2             = "192.168.87.2" -> "192.168.87.52" # forces replacement
       ~ id                            = "VsaWorkingEnvironment-*******" -> (known after apply)
         name                          = "****_netapp_cvo_lab"
       ~ svm_floating_ip               = "192.168.87.10" -> "192.168.87.60" # forces replacement
         # (30 unchanged attributes hidden)
 
         # (5 unchanged blocks hidden)
     }
 ```
terraform 1.0
netapp/netapp-cloudmanager v21.9.4

**Comment by carchi8py** [comment]
The Api does not support it
