### ISSUE TITLE
No description for "aws_credentials_name" in docs for "netapp-cloudmanager_aws_fsx"

### ISSUE THREAD

**Issue by felix-melligan** [NetApp/terraform-provider-netapp-cloudmanager#81]
There is no information about the "aws_credentials_name" parameter in the documentation but it is a required field.

**Comment by lonico** [comment]
We will add this.  From OCCM documentation

To create or manage an Amazon FSx for ONTAP working environment, you need an AWS access key and secret key for an IAM user with FSx for ONTAP permissions. These permissions are different from the permissions required to create a Connector in AWS.

At present, you can create the AWS credentials using the CloudManager UI.  It will prompt for a name, and the AWS access key and secret key.   Once this is done, it takes some time for the information to be propagated in the system.  While this is being propagated, using the provider may report 2 errors:
1. Error: aws_credentials_name not found
2. once the name can be found, the FSx creation may still fail with 
Error: code: 404, message: {"statusCode":404,"message":"Invalid credentials ID","error":"Not Found"}

But it will eventually succeed.

**Comment by lonico** [comment]
Added in November.
