### ISSUE TITLE
Remove requirement for GCP service account JSON

### ISSUE THREAD

**Issue by felix-melligan** [NetApp/terraform-provider-netapp-cloudmanager#82]
Currently the netapp-cloudmanager_connector_gcp resource requires the service_account_path value to be set. This is insecure and often requires the storage of a key within a repository for jenkins builds.

Alternative option would be to use GCP SDK to authenticate using local service account/gcloud auth login.

**Comment by mrobinson-anaplan** [comment]
Allowing the key to be passed as a string would also be an improvement.  It could be supplied from a `google_service_account_key` incantation.

**Comment by felix-melligan** [comment]
@lonico do you think this approach is viable at all? Thanks!

**Comment by lonico** [comment]
We already us aws configure or az login, so I agree it makes sense to do something similar with gcloud.   We may need to understand the dynamics with Eran.

We'll look into google_service_account_key as well.

**Comment by mrobinson-anaplan** [comment]
@felix-melligan @lonico this has now become urgent as anaplan are getting close to deployment. 
I've opened a PR which, whilst not as elegant as we would all like does unblock us.
