### ISSUE TITLE
Unable to fetch public ip of connector

### ISSUE THREAD

**Issue by skumaruvce** [NetApp/terraform-provider-netapp-cloudmanager#88]
Once AWS connector is created, unable to retrieve public IP of connector. It will be good if the AWS instance is returned to user

**Comment by carchi8py** [comment]
We have an internal Story DEVOPS-4854 open for this.

**Comment by chuyich** [comment]
fixed in 22.5.0

**Comment by chuyich** [comment]
fixed in 22.5.0
