### ISSUE TITLE
Add functionality to add SVM to CVO HA in GCP

### ISSUE THREAD

**Issue by felix-melligan** [NetApp/terraform-provider-netapp-cloudmanager#93]
Add the ability to create an extra SVM in GCP for CVO HA through terraform provider and reference that for creating volumes.

**Comment by carchi8py** [comment]
We have an internal Story DEVOPS-4853 open for this issue.

**Comment by roreviakin-clgx** [comment]
Hello! Do you have any ETA for this?

**Comment by rpdowler** [comment]
ETA?!

**Comment by lonico** [comment]
No ETA.  We are exploring the APIs that were very recently released.

**Comment by lonico** [comment]
Released in 22.11.0.
