### ISSUE TITLE
capacity-based licensing

### ISSUE THREAD

**Issue by dereke620** [NetApp/terraform-provider-netapp-cloudmanager#94]
Per a recent deployment with the following tf config, we are seeing the following error with the license:
module.netapp.module.systems["primary"].netapp-cloudmanager_cvo_gcp.this: Creating...

│ Error: license_type must be capacity-paygo

│

│   with module.netapp.module.systems["primary"].netapp-cloudmanager_cvo_gcp.this,

│   on ../../../tf-module-gcp-netapp/modules/system/cvo.tf line 1, in resource "netapp-cloudmanager_cvo_gcp" "this":

│    1: resource "netapp-cloudmanager_cvo_gcp" "this" {

Here is the tf config example with customer info stripped for security:
  ~ netapp = {
      + system    = {
          + primary = {
              + capacity_package_name = "Essential"
              + cluster_subnet        = "netapp-cluster"
              + gcp_volume_size       = "500"
              + gcp_volume_size_unit  = "GB"
              + gcp_volume_type       = "pd-ssd"
              + ha_cluster            = false
              + ha_subnet             = "netapp-ha"
              + instance_type         = "n2-standard-8"
              + license_type          = "gcp-cot-premium-byol"
              + primary_subnet        = "netapp"
              + project               = "xxxx"
              + region                = "us-east4"
              + replication_subnet    = "xxxx"
              + serial_number         = "xxxx"
              + snapmirror_policy     = "MirrorAllSnapshots"
              + source_ranges         = [
              + volume_size           = 500
            }

**Comment by bryanheo** [comment]
According to the validation function, it seems that we have to use either capacity-paygo or ha-capacity-paygo once capacity_package_name is defined but there are three different options ('Essential', 'Professional', 'Freemium') on capacity_package_name associated with different license_type.

`func validateCVOGCPParams(cvoDetails createCVOGCPDetails) error {
	if cvoDetails.IsHA && cvoDetails.WritingSpeedState != "" {
		return fmt.Errorf("writing_speed_state parameter not required for CVO GCP HA")
	}

	if cvoDetails.VsaMetadata.UseLatestVersion == true && cvoDetails.VsaMetadata.OntapVersion != "latest" {
		return fmt.Errorf("ontap_version parameter not required when having use_latest_version as true")
	}

	if cvoDetails.IsHA && cvoDetails.VsaMetadata.LicenseType == "gcp-ha-cot-premium-byol" {
		if cvoDetails.HAParams.PlatformSerialNumberNode1 == "" || cvoDetails.HAParams.PlatformSerialNumberNode2 == "" {
			return fmt.Errorf("both platform_serial_number_node1 and platform_serial_number_node2 parameters are required when having ha type as true and license_type as gcp-ha-cot-premium-byol")
		}
	}

	if !cvoDetails.IsHA && (cvoDetails.HAParams.PlatformSerialNumberNode1 != "" || cvoDetails.HAParams.PlatformSerialNumberNode2 != "") {
		return fmt.Errorf("both platform_serial_number_node1 and platform_serial_number_node2 parameters are only required when having ha type as true and license_type as gcp-ha-cot-premium-byol")
	}

	if cvoDetails.VsaMetadata.LicenseType == "gcp-cot-premium-byol" {
		if cvoDetails.SerialNumber == "" {
			return fmt.Errorf("serial_number parameter is required when having license_type as gcp-cot-premium-byol")
		}
	}

	if cvoDetails.VsaMetadata.CapacityPackageName != "" {
		if cvoDetails.IsHA && cvoDetails.VsaMetadata.LicenseType != "ha-capacity-paygo" {
			return fmt.Errorf("license_type must be ha-capacity-paygo")
		}
		if !cvoDetails.IsHA && cvoDetails.VsaMetadata.LicenseType != "capacity-paygo" {
			return fmt.Errorf("license_type must be capacity-paygo")
		}
	}

	if strings.HasSuffix(cvoDetails.VsaMetadata.LicenseType, "capacity-paygo") && cvoDetails.VsaMetadata.CapacityPackageName == "" {
		return fmt.Errorf("capacity_package_name is required on selecting Bring Your Own License with capacity based license type or Freemium")
	}
	return nil
}`

**Comment by dereke620** [comment]
> According to the validation function, it seems that we have to use either capacity-paygo or ha-capacity-paygo once capacity_package_name is defined but there are three different options ('Essential', 'Professional', 'Freemium') on capacity_package_name associated with different license_type.
> 
> ` if cvoDetails.VsaMetadata.LicenseType == "gcp-cot-premium-byol" { if cvoDetails.SerialNumber == "" { return fmt.Errorf("serial_number parameter is required when having license_type as gcp-cot-premium-byol") } }
> 
> ```
> if cvoDetails.VsaMetadata.CapacityPackageName != "" {
> 	if cvoDetails.IsHA && cvoDetails.VsaMetadata.LicenseType != "ha-capacity-paygo" {
> 		return fmt.Errorf("license_type must be ha-capacity-paygo")
> 	}
> 	if !cvoDetails.IsHA && cvoDetails.VsaMetadata.LicenseType != "capacity-paygo" {
> 		return fmt.Errorf("license_type must be capacity-paygo")
> 	}
> }
> ```
> 
> `

**Comment by dereke620** [comment]
> According to the validation function, it seems that we have to use either capacity-paygo or ha-capacity-paygo once capacity_package_name is defined but there are three different options ('Essential', 'Professional', 'Freemium') on capacity_package_name associated with different license_type.
> 
> ` if cvoDetails.VsaMetadata.LicenseType == "gcp-cot-premium-byol" { if cvoDetails.SerialNumber == "" { return fmt.Errorf("serial_number parameter is required when having license_type as gcp-cot-premium-byol") } }
> 
> ```
> if cvoDetails.VsaMetadata.CapacityPackageName != "" {
> 	if cvoDetails.IsHA && cvoDetails.VsaMetadata.LicenseType != "ha-capacity-paygo" {
> 		return fmt.Errorf("license_type must be ha-capacity-paygo")
> 	}
> 	if !cvoDetails.IsHA && cvoDetails.VsaMetadata.LicenseType != "capacity-paygo" {
> 		return fmt.Errorf("license_type must be capacity-paygo")
> 	}
> }
> ```
> 
> `

Per the info above, even with a BYOL license, we should always be using ha-capacity-paygo or capacity-paygo if we are going to define the capacity_package_name = "Essential" "Professional" "Freemium". If we use this method, will it still pull from the BYOL/Eval license inside the customer's digital wallet or will ha-capacity-paygo or capacity-paygo bill to the marketplace subscription? To me, this should be a BYOL license with capacity_package_name defined + serial_number defined.

**Comment by lonico** [comment]
Our understanding is that you should always use by-capacity.  This is what the Cloud Manager asked us to do.  But we're checking with them to make sure.

**Comment by chuyich** [comment]
@dereke620 There were two categories of license: **by Capacity** or **by Node** in CVOs. We don't support **by Node** license for the new customer any more. In your terraform configuration, you use capacity_package_name (by Capacity) and serial_number with gcp-cot-premium-byol (by Node). What license do you use?

**Comment by dereke620** [comment]
@chuyich We have a capacity-based BYOL license. What I need to confirm is that if we deploy with the following variables, it will draw the licensing from our BYOL license or from the marketplace subscription?
capacity_package_name = "Essential"
license_type ="capacity-paygo"
serial_number = "serial number from license in CM Digital Wallet"

To me the term capacity-paygo references a marketplace subscription vs. the capacity-based BYOL option. However, if you tell me that to use any capacity-based licensing BYOL or marketplace you should use capacity-paygo or ha-capacity-paygo and define the package name then we should be good.

**Comment by lonico** [comment]
Oh, if you have a capacity based license, whether it's BYOL or PAYGO, you should use capacity-paygo or ha-capacity-paygo.
I know this is confusing, but this is what we've been told (I'd think they could just have created aliases to make it more friendly).

Now, the question should really be addressed to the NetApp Cloud folks to make sure this is correct and that you are not charged.

The Wallet is actually supposed to make this easier.

**Comment by carchi8py** [comment]
This was fixed in 22.4.0
