### ISSUE TITLE
Cannot change firewall_tags on netapp-cloudmanager_connector_gcp

### ISSUE THREAD

**Issue by bryanheo** [NetApp/terraform-provider-netapp-cloudmanager#97]
Hello

We are deploying multiple connectors in the same GCP project but in different regions.
If I deploy the connector through Cloud Manager UI then I can apply the custom firewall tag on the SVMs but If I deploy it through terraform, it always shows 'firewall-tag-bvsu'. This can be an issue if we have multiple connectors in the same GCP project because all the connectors will use the same firewall tags.
Are there any ways to customize the firewall tag on the connectors via the NetApp-cloudmanager_connector_gcp like Cloud Manager?

Firewall Tags on the connector in GCP deployed via Cloud Manager:
![image](https://user-images.githubusercontent.com/12592663/165059536-eb89c852-904c-4d84-9460-928f3a421b01.png)

Firewall Tags on the connector in GCP deployed via Terraform:
![image](https://user-images.githubusercontent.com/12592663/165059900-1db033e0-44b4-4830-be16-2cc02dab1cbd.png)

**Comment by lonico** [comment]
You can use `tags` to add additional tags.
```
tags = ["testtag1", "testtag2"]
```

![image](https://user-images.githubusercontent.com/5272858/165142937-601e9ba4-6cb9-4c60-b427-aa2ad613a24e.png)

**Comment by bryanheo** [comment]
Thank you for your message 
As you suggested, I made firewall_tags 'false' and added tags with custom firewall tags and it works. Many thanks again

**Comment by bryanheo** [comment]
Solved
